version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - franchise-net

  franchise_app:
    image: franchise_management:latest
    container_name: franchise_app
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=70 -Djava.security.egd=file:/dev/./urandom
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/franchise_db
    depends_on:
      - mongodb
    networks:
      - franchise-net

networks:
  franchise-net:
    driver: bridge